### ISSUE TITLE
'learn' command resembles run but with no save

### ISSUE THREAD

**Issue by knightofknee** [learn-co-curriculum/hs-js-cartoon-collections#1]
This could just be me, but I am used to the run command saving then running (I learned in Mumps so I don't expect to be typical), so when I submitted with "learn" repeatedly with no changes in result I assumed my syntax was always wrong. Would it be more consistent for learn to be the same? Or would that not make sense at all, given that we are really submitting our saved code to an outside source and getting a reply?

**Comment by gj** [comment]
Hi @knightofknee !

The gem shouldn't be auto-saving your code — that's way outside the scope of its intended behavior. Students should be saving and then running the test suite, as you figured out. 🙂
