### ISSUE TITLE
Test is missing an expectation

### ISSUE THREAD

**Issue by paseremetis** [learn-co-curriculum/hs-js-cartoon-collections#3]
In the JS Cartoon Collections lab, the "summon Captain Planet" test is missing an expectation on line 20. The description of the "summon Captain Planet" test requires that the user capitalize each element in the planeteerCalls array, and then add an exclamation point to the end of that element. However, the expectation listed on line 20 only lists that the item should contain an exclamation point. It does not mention that the item should be capitalized as well. As a result, the "summon Captain Planet" test passes when the user adds an exclamation point to the end of each item, but the test only passes when the items are lowercase. The test fails when the items are uppercase. 

JS Cartoon Collections Lab "summon Captain Planet" test, Line 20:
https://github.com/learn-co-curriculum/hs-js-cartoon-collections/blob/master/test/index-test.js#L20

**Comment by aviflombaum** [comment]
Closed by d39c26a5469b1cc253d15c3bb35c74357575ee39
